import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "@/components/BlogCard";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { useState } from "react";

const graphcms = new GraphQLClient(
  process.env.NEXT_PUBLIC_HYGRAPH_CMS_ENDPOINT
);

const QUERY = gql`
  {
    posts(orderBy: datePublished_DESC) {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      tags
      coverPhoto {
        url
      }
      createdAt
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  const [filter, setFilter] = useState("");
  const filteredPosts = posts.filter((post) => post.tags.includes(filter));

  let postList = [];

  if (filter === "") {
    postList = posts;
  } else {
    postList = filteredPosts;
  }

  return (
    <>
      <Head>
        <title>Franklin Assa Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.home}>
        <h2 className={styles.home__title}>Blog</h2>
        <div className={`${styles.home__container} ${styles.grid}`}>
          {filter ? (
            <div className={styles.filter}>
              <div>
                posts tagged <span>#{filter}</span>
              </div>
              <div onClick={() => setFilter("")}>
                <span>see all posts</span>
              </div>
            </div>
          ) : null}

          {postList.map((post) => (
            <BlogCard
              title={post.title}
              author={post.author}
              coverPhoto={post.coverPhoto}
              key={post.id}
              datePublished={post.datePublished}
              tags={post.tags}
              slug={post.slug}
              setFilter={setFilter}
            />
          ))}
        </div>
        <Footer />
      </main>
    </>
  );
}
